/*
 * Auto-Generated System Concurrency Model
 * Generated by Real-World IT Audit Engine
 */

#define WORKERS 3
#define MAX_QUEUE_CAPACITY 3

chan request_queue = [MAX_QUEUE_CAPACITY] of { int };
byte active_threads = 0;
byte deadlock_risk = 0;

proctype Worker(byte id) {
    int req;
    byte processed = 0;
    do
    :: processed < 2 ->
        if
        :: request_queue ? req ->
            atomic {
                active_threads++;
                if
                :: (active_threads > 10) -> deadlock_risk++;
                :: else -> skip;
                fi;
            }
            
            printf("Worker %d processed request %d (active: %d)\n", id, req, active_threads);
            
            atomic {
                active_threads--;
                processed++;
            }
        :: else -> skip;
        fi;
    :: processed >= 2 -> break;
    od;
}

proctype RequestGenerator() {
    int i = 1;
    do
    :: i <= 3 ->
        request_queue ! i;
        i++;
    :: i > 3 -> break;
    od;
}

init {
    byte w = 0;
    atomic {
        run RequestGenerator();
        for (w : 0 .. 2) {
            run Worker(w);
        }
    }
}

/* LTL Safety Property: Active thread contention must never exceed safe hardware threshold */
ltl safe_contention { [] (active_threads <= WORKERS) }
